apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ace-bar-pipeline-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ibmc-file-gold-gid
  volumeMode: Filesystem