apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
  name: functional-test
spec:
  params:
  - name: previous-is-genenration
    type: string
  - name: previous-deployment-revision
    type: string
  - name: release-name
    type: string
  - name: is-source-directory
    type: string
  - name: key-certs-secret-name
    type: string
  - name: client-key
    type: string
  - name: client-cert
    type: string
  - name: ca-cert
    type: string
  - name: endpoint-path
    type: string
  steps:
  - env:
    - name: BASIC_AUTH_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: basic-auth-rest
    - name: BASIC_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: basic-auth-rest
    image: quay.io/openshift/origin-cli:latest
    name: resolve-route
    resources: {}
    script: |
      #!/bin/bash

      set -e

      SLEEP_TIME_SEC=10
      RETRIES=20

      wait_until() {
        condition=$1
        message=$2

        retries=$RETRIES
        until $condition || [[ "$retries" -eq 0 ]]; do
          retries=$((retries - 1))

          sleep $SLEEP_TIME_SEC
        done

        if [[ "$retries" -eq 0 ]]; then
          echo $message
          exit 1
        fi
      }

      url_is_ready() {
        url=$1
        curl -s \
          -u $BASIC_AUTH_USERNAME:$BASIC_AUTH_PASSWORD \
          --request OPTIONS \
          --cacert /client-certs/$(params.ca-cert) \
          --cert /client-certs/$(params.client-cert) \
          --key /client-certs/$(params.client-key) \
          https://$url 2>/dev/null
      }

      route=$(oc get routes -l app.kubernetes.io/instance=$(params.release-name) -n dev -o jsonpath='{.items[?(@.spec.port.targetPort=="https")].spec.host}')
      echo -n $route > /shared/route.txt

      wait_until "url_is_ready $route/$(params.endpoint-path)" "Route is not set up"
    volumeMounts:
    - mountPath: /shared
      name: shared-volume
    - mountPath: /client-certs
      name: certs
      readOnly: true
  - env:
    - name: BASIC_AUTH_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: basic-auth-rest
    - name: BASIC_AUTH_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: basic-auth-rest
    image: image-registry.openshift-image-registry.svc:5000/ace/newman
    imagePullPolicy: Always
    name: run-test
    resources: {}
    script: |
      #!/bin/bash

      set -ex

      route=$(cat /shared/route.txt)

      #route=create-customer-details-rest-https-dev.ace-prod-ref-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud

      echo $route

      test_file=$(workspaces.workspace.path)/$(params.is-source-directory)/test/newman/test.json
      if [[ -e $test_file ]]; then
        newman run \
          --ssl-extra-ca-certs /client-certs/$(params.ca-cert) \
          --ssl-client-key /client-certs/$(params.client-key) \
          --ssl-client-cert /client-certs/$(params.client-cert) \
          --env-var username=$BASIC_AUTH_USERNAME \
          --env-var password=$BASIC_AUTH_PASSWORD \
          --env-var host=$route \
          $test_file

      fi
    volumeMounts:
    - mountPath: /shared
      name: shared-volume
    - mountPath: /client-certs
      name: certs
      readOnly: true
  volumes:
  - emptyDir: {}
    name: shared-volume
  - name: certs
    secret:
      secretName: $(params.key-certs-secret-name)
  workspaces:
  - name: workspace
