apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: basic-auth-rest
  namespace: dev
spec:
  encryptedData:
    password: AgA29Dqqe50fDUrsCT/rG7qmd9qtStB6Gt6dibPuEg5hE0QuWpJ2aq/44PCJPLqRUINFSOtsqBCq3QlpEFns2YF4G2AaIwUbrj25DNq57Ue+s5bhNecT8Fjk9pCPxIp0cYQbrHZzjij9NZrZ0Xs7UV2cnJILPFVPjUFF97u3212yPhsdgxWVnqc//FwuPDugWU0ZxbDERH7tzvVq9OxhIox0Q2gmsdWISRC+q65/Dt3yncqVEzy5wkIQibl8iFADl0KRh0QMYa9J+YzI+UIoVUqOLNASx3vVcpaXdJLaNHnLHj+6+GICP7528qHD9K6+cpdTLx5hcyE/qa1wM+BU46qcfn7hczf0W3TxzHZMeCWsPlvu8qdjEbkKRxgzNtei9N+onb3JbTYCmkle+ECHuvka0G8mjSH+GgVUjnp7MQGhskNV6shkhdTPIrnXRP0B6nOow/6CsumoEPs05zPgwnF9Cpu6C1Gf+G7tEJmMov9OPszUDOA7jVyZiCDk7m/6WgeDc8OquINzDq6hJdu0BOC0cNObc/mvzUGuO0SBHutHDidenBqRJloSqT6iGAK1Szh23jRh2HrQNe9gWqzRJs/XX+y+k18PlmraJBJPflhB2TsuDj43g2mZsheYyv3CDARxn4v8PCfeuzu2DwbjDkSOInQOAmc2QZd/seHV9LJb1PngdCAQ4dOMJQmzEcpS658EQs/ZO3b5tQ==
    username: AgAmGNw/QQXPS6JFB7yc1MJsWRVMsTmIJ77zmcqyq812ARJA0uNn6v4BDzfOZKP9tFHpnqgTvJt55n/FlbIEy6R9SPGqRfYb+VzfxnGmsaNSWl9S5e+mrQzVJdmSFBWiV3iQ9FmdXsi1HL8bbGcXOx0kmzY8+C0VLcdWiwclFvweUzeASeuENRQNmG8MKa+NjzpUk0HNbN0d7OljMMfDvSqFwfRmP84fSfcEJWzGrNxvFgt7z3v5Ir1eGh8WMPZVQ9dzwLkPc+avRxJqiqLcBV6qGwuFs4rKe/71lrAIo7ykjhzc2l0nehyLwNAFbGSxRBeAh5kfb2TkQaU+kqbP3c/HzsDxLWHbOTwsqlf3CJ9moQZN5aUH+OFV1znBn0SLlk29Bq/pi6U+7d/y5KnwvfULSG8axUncn0tdYHiDcXmafWwTAqZsX1CM+KCyA4tH0+MErb9He7VPPSD3tFuhx30PBaYH9uiNArFT6OQXz61566PyjhKawyeCu89GjQlIMtoPTi/gXDhXk3wh4ekOeHBxAGNC6CdPx+NkEM6xgS2b1QQ8tzYzyDzMPAjuZqeQlcvHqhcj32xHhI4tdsOrDzD8XrAIHSzrTxIhtHO4gkB/jeWaoPQuwqU/YZViF1zJTYxO24y4t6GJZL1B4sjPAFQ5nD4YQ/y+y370C9J0GS+97rB0XclozYyLBVphLRezlOHJoty+aaSI
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: basic-auth-rest
      namespace: dev
    type: Opaque

