apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ace-config
spec:
  params:
  - name: is-source-repo-url
    type: string
  - default: is-source
    name: is-source-directory
    type: string
  - name: is-source-repo-private-key
    type: string
  - name: is-infra-repo-url
    type: string
  - default: is-infra
    name: is-infra-directory
    type: string
  - name: is-infra-repo-private-key
    type: string
  - name: is-config-repo-url
    type: string
  - default: is-config
    name: is-config-directory
    type: string
  - name: is-config-repo-private-key
    type: string

  - name: git-ops-repo-url
    type: string
  - name: git-ops-repo-private-key
    type: string
  - name: git-ops-parent-directory-relative-to-workspace
    type: string
  - name: git-ops-destination-directory
    type: string
  - name: git-ops-kustomization-path
    type: string
  tasks:
  - name: clone-is-source
    params:
    - name: url
      value: $(params.is-source-repo-url)
    - name: subdirectory
      value: $(params.is-source-directory)
    - name: deleteExisting
      value: "true"
    - name: sshPrivateKey
      value: $(params.is-source-repo-private-key)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: clone-is-infra
    params:
    - name: url
      value: $(params.is-infra-repo-url)
    - name: subdirectory
      value: $(params.is-infra-directory)
    - name: deleteExisting
      value: "true"
    - name: sshPrivateKey
      value: $(params.is-infra-repo-private-key)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: clone-is-config
    params:
    - name: url
      value: $(params.is-config-repo-url)
    - name: subdirectory
      value: $(params.is-config-directory)
    - name: deleteExisting
      value: "true"
    - name: sshPrivateKey
      value: $(params.is-config-repo-private-key)
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: resolve-props
    params:
    - name: is-source-directory
      value: $(params.is-source-directory)
    runAfter:
    - clone-is-source
    taskRef:
      kind: Task
      name: resolve-props
    workspaces:
    - name: input
      workspace: shared-workspace
  - name: create-config
    params:
    - name: is-config-directory
      value: $(params.is-config-directory)
    - name: is-infra-directory
      value: $(params.is-infra-directory)
    - name: is-configuration-keystore
      value: $(tasks.resolve-props.results.is-configuration-keystore)
    - name: is-configuration-truststore
      value: $(tasks.resolve-props.results.is-configuration-truststore)
    - name: is-configuration-setdbparms
      value: $(tasks.resolve-props.results.is-configuration-setdbparms)
    - name: is-configuration-serverconf
      value: $(tasks.resolve-props.results.is-configuration-serverconf)
    - name: is-configuration-policyproject
      value: $(tasks.resolve-props.results.is-configuration-policyproject)
    - name: is-configuration-loopbackdatasource
      value: $(tasks.resolve-props.results.is-configuration-loopbackdatasource)
    runAfter:
    - resolve-props
    - clone-is-config
    - clone-is-infra
    taskRef:
      kind: Task
      name: create-config
    workspaces:
    - name: workspace
      workspace: shared-workspace
  
  - name: git-ops
    taskRef:
      kind: Task
      name: git-ops
    params:
      - name: url
        value: $(params.git-ops-repo-url)
      - name: revision
        value: master
      - name: sshPrivateKey
        value: $(params.git-ops-repo-private-key)
      - name: kustomization-path
        value: $(params.git-ops-kustomization-path)
      - name: filelist
        value: $(tasks.create-config.results.configurations)
      - name: parent-directory-relative-to-workspace
        value: $(params.git-ops-parent-directory-relative-to-workspace)
      - name: destination-directory
        value: $(params.git-ops-destination-directory)
    runAfter:
    - create-config
    workspaces:
    - name: shared-workspace
      workspace: shared-workspace
  
  workspaces:
  - name: shared-workspace
