apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-ci
  annotations:
    argocd.argoproj.io/sync-wave: "400"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: ci
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: 1-apps/instances/namespace-ci/ace-app/config/ci/base
    repoURL: https://github.com/vgadepal/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy: {}
