apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-prod
  annotations:
    argocd.argoproj.io/sync-wave: "400"
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: 1-apps/instances/namespace-prod/ace-app/config/prod/base
    repoURL: https://github.com/vgadepal/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
