apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-rest-dbparms.txt
  namespace: staging
spec:
  encryptedData:
    configuration: AgAbho9Wlf6iNj/ByxGJeMDNwZrzqV3msMs/gQVIzXYummDPOs3+WIbvjyJAf+lgUOXX6bxn5cpNtMAdHBslh2WVY/oraz8tbivNEmaPK9Wi5ucePAor5RanuBtSkRBVKKjZjcO/K83N51lYNvQIK6nBYttqzD+berYt3Uilo7ih0/TE8DcJ1BsvYqklE2XZh1C5ocBIaA2nJ+roUprpSxsUScFJTS8cAbLwAo1R9ppQ4JP8vqXpuD+/7ctecF+0K4tL/3sFFIgkhQjRzUEJ2b0EtqX+p1Xdh9qeXiZb5bxzQkkcR/cWndO6RM1lvzl/5Yc88UBFsvQDxKHrLCFWVctZSSbasq6Z+YKefSnrEn3imGivMDuq9TK9EE+P1uP7/B2fiX6DFGsAgDJeiHT7WCKwG1Awu62YnXRrDNoQlpKUk2Nm044DOL0lEPu+2AUcKVRBMJMCwrF3y2gnKP6rdJD9ss1xhaD5JtDCY7qwBF7QnVoh4x7vlpYano2T59wuQobqNoJtGHaO+ZTBB/zBBf+bBm6HHJaFlxh7eryWOEgklGH9B2P+42OuLfR6EwKxZWjw8g36SnuCFkN6JOR16yb3AG+2hsKAy1EjTqq64EzCwwUT0KG+r9ydihDyifMYRwC+PvPKzg4knIobt9GEtiwQWyzz49a1Romjs2gmxRsltlxiRBno9AVNMcjZNLE0+ndjIVvbNHL0rzsuifJfaCmidLkT3VAxfxl7Tx7NGQ30eblCHoM9LW9BpDbznYE1xEXnbFhVcH5xUkmO+QxGyy84hskZVP+0DF8ui9GCZIO2KUwnMl5n5ekIaZDiSFL+rlcz0khfXP2kbye2QMoir0WqJr49VLlOxasXSB0lTX6X4HJ/t0S7nbUsigAYjm49x3s8hF5OhLeeaPcNARLdfwOEFjT6Qr1h7Lm5dZn45uruqNuTPIqx9tm0ARZXM33duyXI2WQiGipKQuSTQxUirAkomQVWfvJhHblni+hJX8vyBChFeEQ+EqK38ppzpE35LpmxRWdBzWqBsaW6/tyD7jNytsiLQdptuqE2a9y4FGQ9ujIF54L/s5SME/DX+QvL1J9EpQ==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-rest-dbparms.txt
      namespace: staging
    type: Opaque

