apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: instana-agent
  namespace: instana-agent
spec:
  encryptedData:
    key: AgAEeEC41gWho9otudOhh/0J6hGsp6IxcApS7yfC8Fov5P8h41KKtEPGMfJz8njkiavLlzEP1mRo4ZXkY+HHpDzCoc+ygsQJxwxoYXZOy9CuzHxInnNd6qUlhc953puC2yJr2CGJA0oljeNjIQn+vmv55OI0sGpfFtkn/iFU+490gI66zvDJ3+kYo6nwZhWzX9bATIvKVU2pJgTv3wyXQWDZsEVOZULQCDcPToX+JCkHY+xODXANPW8XqUGSrJJwdibRsP/Gc798lAmIYr0O1K/8dnA192/obKGcI4+A8bk4XP/86VceTZnQMyANptuYYKNHTysmb4KvdHpc+wpou6TN/KDT705suh4yVMt6AYU8E7GLcpywiD2SAXCX/UErW1tWQzDcXeX77WbY0KyrHw/cbALVYoEJdfpDOXt+64cxRYhHY4F9l8mLwInoB7Wdu2eoNSZjZRES+5zUbooauXSB1qyOlfoPE+FAjWkrsRpLIfx3AjlofTw0ZEcBvJ1IZlAo/rvseoo5W16HPajOvKVDPwMwRIX6bO8mVTfIqtDvfysNvhaCQFglq2wQW4IeUs5YDJ1+BGKH6MvLzjPJ7M4Eez5Mk0funX32cQY34ewnNZoTWNmnp3FYWFs2Qg+I+yqjTh/s499uL8OyziKSirAInpTTkite8ASVJs1MPRgR1thEp/o7rSlE4l3h+gSLJmAPJuSDNgBkxiE2DalEYiRXSiVFcTWO
  template:
    metadata:
      creationTimestamp: null
      name: instana-agent
      namespace: instana-agent

