apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-ace
  annotations:
    argocd.argoproj.io/sync-wave: "100"    
spec:
  destination:
    namespace: ace
    server: https://kubernetes.default.svc
  project: infra
  source:
    path: 3-infra/namespaces/ace
    repoURL: https://github.com/vgadepal/multi-tenancy-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
