apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ace-config
spec:
  params:
    - name: source-git-url
    - name: source-repo-name

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: ace-config-$(uid)
      spec:
        params:
          - name: is-source-repo-url
            value: 'git@github.ibm.com:cpat-int-samples/createCustomer_REST_V1.git'
          - name: is-source-directory
            value: is-source
          - name: is-source-repo-private-key
            value: id_create-customer-rest-v1
          
          - name: is-infra-repo-url
            value: 'git@github.ibm.com:cpat-int-samples/eaglebank-ace-infra.git'
          - name: is-infra-directory
            value: is-infra
          - name: is-infra-repo-private-key
            value: id_eaglebank-ace-infra
          
          - name: is-config-repo-url
            value: $(tt.params.source-git-url)
          - name: is-config-directory
            value: is-config
          - name: is-config-repo-private-key
            value: id_eaglebank-ace-config
          
          - name: git-ops-repo-url
            value: git@github.com:vgadepal/multi-tenancy-gitops.git
          - name: git-ops-repo-private-key
            value: id_multi-tenancy-gitops
          - name: git-ops-kustomization-path
            value: 1-apps/instances/namespace-dev/ace-app/config/dev/base/kustomization.yaml
          - name: git-ops-parent-directory-relative-to-workspace
            value: configurations
          - name: git-ops-destination-directory
            value: 1-apps/instances/namespace-dev/ace-app/config/dev/base/configuration

        pipelineRef:
          name: ace-config

        serviceAccountName: pipeline

        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: ace-rest-ws

