apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgAM7aiBIpd8OAZelw+hzB+ACg2IRKuMdKe3XLC50PRJVpa9dTNJcNwpywrnYl9qK3R1y45u84S6klk5Le+2zqbnTuC/7Cod/tC3T7HBZ+TpsLCltJlAtQV+50bixinDzU/w7swZV23+q6B0MtmLVM2AnZWnpe7qFPMiHTOE8ppITebxoTiO972vUFMIo0YsJv+kOXr2YMIf2TK3XOj9nBxSHkvtw38p3WdC3UBVcLQDgpMQwNnWcFjBe4u7Ww3BGorzIlx8/3zLQ9FXE+NMrCttDEbN/QJ+jHRkwFSInyM7oBgRfWFFUEr6B7fr7HOaSGW28idWxUky5XnAQnibsLIdhxPVE4JgF9YKHvk3/ko/7NFmDdspyXtqn4lfSIaOVAKjEuUv/tlLh/lRB6HO8Rvq7pfpYE9h1Z5jVP8bVk1pIk9jiay6bJ5PsCLQzGyYKNZlE2jOHx6Q6Rb1EkA84ORwM/2uvvGX6wVCTk8gX9uzynaJGNKd40UQ//JpARpEPyab9q0Q5SFzrGPMXT6ZGd3BIOW2f0jTzM2SStixfxzsCbDxcpeXSyBiijAhktEA3liUw4DHVer7hewJo94OMVut+WV+ie1t2AmmKhQaF6uUgeVNuhJxNDrFo7rfnrAJyPMRHP//E5n2XvWOLEN2wAZe4f0l3fbyGPExbE7e1ziblfuVR6OZJr1nWyIVQ5nHpiqM8kyLPBV8ro/ehIFsyuSWu99T7wqXoHKN4piy/CEkv/Dkn85CHbB1hg==
    username: AgAiu5aaS8qAvODa+EBRXbYjMgU2LgpFBQbdnR2ivqXRGhEQ1kU8pAYqYN2MgxisnMsy27DynayQawMM1ImjGFJ5Z3f2UzZhnltyyAlmcqYhdJ9j/1lW3XJKNM7W4x6NlZnR/ay9dWb8YK3NHYB9dQwJUlm5XkRfrEidsg7ta4L2CunK6y/oS+yR+ByCVuASKU3ESxFPHMt+dW/Ar9LeDczCbA6BjzzyHaYGWDAPDk51KIQGQMRp+oD0x1E5BwMoR/wQq4VVxeJVnmQ7NM3OwULDcSr/fMVewjF3Lj5Rpv1uxYs6YI/p7ssrn8dPomMN7+EUiVm0DxSUiOBiADS4IHpQSckCkIYW4hDmtNxQDRrARvn6tVg5QwUAiNpx8TUu8xkQ5UUgHnatkqDfrNE9V4oVA46AHuvH3gBZMUbp8dV/GsMEhZDuOWWvfxWp+9YIZjzYphRti6qrOaejXgeXut/c+w8lTwjG4Gunpgu3xMzQzxDj61iZS31ODiWO8+y0svRfYILxZDc72+u9EjI9g8FqpoBnDpR6p+K6J1pvuIRiU2MNx6tZjslptPx3jZfT+7aAPyfAqQCcb02JBQUC8HJCCXtntPTfiTcb2dw/hYss5KuCEtdgdpZE2tlGeCMvJlvtBZsjxNSxj9Z9teZv3PWWFGsXDdptIOSX4wL4BuSrrQBvULxetAfEx0ZDrnHjYY38+CxbKcr9j0j7Eg==
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: Opaque

