apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-credentials
  namespace: ci
spec:
  encryptedData:
    password: AgA580BX80lUcI+SLxOcUJ3L5LlYnZ/d79mLgyg/K/11spYQfHGuJTC+HB2xhiqlREw0CINB+cyUkirKAQmHPneVD8zQy7a/9eeMaiNCX92/kYU9LWwlxBJtf0rqaCCmkgRcms7CIlOQOf0Z6E/p4+P/rKiglJECyPktzI1Yib9Tdd3MQ2rOJnpJfoUhpO+vbz6bjvFdZ6fj3RAeoejqwyKo5RHrnUZt/+JxhdavIcWrgP+oxpkXv9MUfWIrn4zq1IXB/OLiNfzILEg+5M4alZp4JKjKLg9R1YyFGXG1eN/hvceJk6I0QGdssnrdWNyIZy8EWRekdrDWgEhfNbsAQQYW9jJDzk82qvYc4bzNx23Z22I+wsA6kGs/it/OVgm0KaQKf8GPEi+3gsURsidREsPGgmST1lRC7rlnwhBxgTyEv5qPtMSIRhFCMDRVQLbQSOZzlX+QCcv40Ko+o+n9mwvfE2cZS2vt3BCfQFnJTC7RlIyYRTUMQ62hb3i/JIlF/zPsiNiEeMqiD442YUgqWWHDkVUE2L5opNt4uxnZOIBIgNvFtfvbQnoPirLRPKNB6Roq0K1iKLlBcpGDAojcVz3TQ3fjC8QpbI0/FJbzjt0i8yg6jKYeITUTsMjs1My7MOaW4es74QfmHBbB9ESEWd3ggKXfk6ELmB7AQRaEpJrMoXSg0DzHoFoXxSAQ2wxOxHyGRplNq3Sl0VDOxgW3uYqzvMElmo6OHGspMmLT4tAfGq2SSE0csM9m
    username: AgBVm3Wb2vSD/l/Xb3a2N5ewmYlr5XZS7DmYqBjRQZ70fR/+YaX2+g/pSA0oQ+adCNsuS8STQ+svTNYgu/IXU86lnOoT8ZWcWCZjRENjXnsEElZ2oTV0PVuTW6cnvxSZEAaYWRqnVE/m8INOpqZrVbHMOgj52O8Eete4404pBJR7FAedO70ho7h1fVIuTdwsmti9WZBCE2yx7BqY+WCa/DNXcsh5uufIUvhWHULfgaE9oVt1qN4wiMmfQ4kGkE38AuZ4lOynQv2HhCb0r4w2kB+91dZVRQPt7qwPyPCGRL5FIe483j/uJpmBMVMBqeQqPcvg6KeROs+MeXXyamysiGdyDudaSltnCxO7f6+/M+dKfNKUyb1p/lTbYUtU+bPdMZoOKIUxcr9/LORK/NyOiaRnnJZMPfH/81lPuA101QFtztRH+GB2CEimSg9LKLDWzc5IWzDpsbDm7r+rNeSAQzGADq7Jgn+9Dr2rYeVjRxQBrm5L1NbLdn2E1jfnWmnfZozibhWwa1dshZQKA2+71BLTdbKpLM+jWigowC3D19qjBW62tVDKau/HZCEoym32bC295PLBDr6egUEe/jmOdP9JGAyCQF3rj/P5NxOsLWT+zcwWifXzyrarnxzy90dqXh79eNuta984zf9Dbgmb6jxX9smPoUAbbccBKF9FPXtJKqg3cyIeV5bs/UoVQtQDJJer3Qmmlwi3RA==
  template:
    metadata:
      creationTimestamp: null
      name: git-credentials
      namespace: ci
    type: Opaque

