apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-repo-ace
data:
  branch: master
  host: github.com
  org: vgadepal
  owner: vgadepal
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops
  url: https://github.com/vgadepal/multi-tenancy-gitops.git
